server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/what_to_by
    username: postgres
    password: 1217
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

application:
  security:
    jwt:
      secret-key: Xq1Eosxs/nDQiGhH92bu3gNRgkhgdYcgV0hNn9/rvZMdHBBlvTBNn3Ngnr/mW9eE
      expiration: 10D
      refresh-token:
        expiration: 30D



