server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://92.255.176.96:5432/diploma
    username: postgres
    password: A@8fxojs2d
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
