server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://92.255.176.96:5432/diploma
    username: postgres
    password: A@8fxojs2d
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


  mail:
    host: smtp.yandex.ru
    username: sagiem
    password: ullgduypnebgwucx
#    qizbadipiehqrkjl
    port: 465
#    test-connection: true
    properties:
      "mail.transport.protocol": smtp
      "mail.smtp.auth": true
      "mail.smtp.starttls.enable": true


application:
  security:
    jwt:
      secret-key: Xq1Eosxs/nDQiGhH92bu3gNRgkhgdYcgV0hNn9/rvZMdHBBlvTBNn3Ngnr/mW9eE
      expiration: 10D
      refresh-token:
        expiration: 30D


